#pragma config(Motor,  motor6,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor12,         rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "RobotCCompatibility.h"
//ChA: Left Joystick, Y-axis
//ChB: Left Joystick, X-axis
//ChC: Right Joystick, X-axis
//ChD: Right Joystick, Y-axis
const int pickupMotorSpeed = 10;
typedef struct {
	int left, right, theta;
} TMotorControl;

int min(int a, int b, int c) {
	int m = a;
	if (m > b) m = b;
	if (m > c) m = c;
	return m;
}

//https://stackoverflow.com/a/19288271
int mod(int a, int b) {
	int r = a % b;
	return r < 0 ? r + b : r;
}

//https://robotics.stackexchange.com/a/2016
void angleToThrust(int r, int theta, TMotorControl &t) {
	theta = ((theta + 180) % 360) - 180;            // normalize value to [-180, 180)
	t.theta = theta;
	if (r > 100) r = 100;                            // normalize value to [0, 100]
	int v_a = r * (45 - mod(theta, 90)) / 45;        // falloff of main motor
	int v_b = min(100, 2 * r + v_a, 2 * r - v_a);    // compensation of other motor
	if (theta < -90) {
		t.left = -v_b;
		t.right = -v_a;
	} else if (theta < 0) {
		t.left = -v_a;
		t.right = v_b;
	} else if (theta < 90) {
		t.left = v_b;
		t.right = v_a;
	} else {
		t.left = v_a;
		t.right = -v_b;
	}
}
task main() {
	setColorMode(port1, colorTypeRGB_Hue_Ambient);
	while (true) {
		int x = getJoystickValue(ChB);
		int y = getJoystickValue(ChA);
		if (x > 100) x = 100;
		else if (x < -100) x = -100;
		if (y > 100) y = 100;
		else if (y < -100) y = -100;
		//https://stackoverflow.com/questions/40363809/faster-way-to-go-from-cartesian-to-polar-in-c
		float radius, angle;
		radius = sqrt(x * x + y * y);
		angle = radiansToDegrees(atan2(y, x));
		angle -= 90;
		if (angle < 0) angle = 360 + angle;
		angle = 360 - angle;
		displayCenteredTextLine(2, "%d", (float)getColorHue(port1)*(360.0/255.0));
		displayCenteredTextLine(3, "%d", (float)getColorSaturation(port1)*(100.0/255.0));
		displayCenteredTextLine(4, "%d", (float)getColorValue(port1)*(100.0/255.0));
		TMotorControl t;
		angleToThrust(radius, angle, t);
		setMotorSpeed(leftMotor,t.left);
		setMotorSpeed(rightMotor,t.right);

		/*if(getJoystickValue(BtnLUp)) setMotorSpeed(firstPickup,pickupMotorSpeed);
		else if(getJoystickValue(BtnLDown)) setMotorSpeed(firstPickup,-pickupMotorSpeed);
		else setMotorSpeed(firstPickup,0);*/
	}
}
